// "use client"
import type { Metadata } from "next";
import NavigationBottom from "@/components/molecules/navigation-bottom/navigationbottom";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="justify-center items-center flex w-full h-screen">
            <div className="justify-center items-center flex w-[350px] h-full relative border-2">
                <div className="w-[350px] h-full relative">
                    {children}
                    <NavigationBottom />
                </div>
            </div>
        </div>
    );
}
